// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHlwhIPSrR9NFLuVKGsfsOd0jQrf9QgU',
    appId: '1:516307748229:web:36d60fb036f9bb8e36b0ec',
    messagingSenderId: '516307748229',
    projectId: 'voyage-33a62',
    authDomain: 'voyage-33a62.firebaseapp.com',
    storageBucket: 'voyage-33a62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXp2tL3XZxhR16eGMW8eemCSK3ZOH2Y4w',
    appId: '1:516307748229:android:13b70788e5c1b7be36b0ec',
    messagingSenderId: '516307748229',
    projectId: 'voyage-33a62',
    storageBucket: 'voyage-33a62.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtKZ0iv2cSBtntHeGphhSMvY80qIBOYs',
    appId: '1:516307748229:ios:0e3d040c8690eb6136b0ec',
    messagingSenderId: '516307748229',
    projectId: 'voyage-33a62',
    storageBucket: 'voyage-33a62.appspot.com',
    iosBundleId: 'com.example.app2',
  );
}
